Added Bandit security analysis.
OperationCode/back-end pull request #3
Opened 2019-05-22 16:27 UTC by garyray-k

Included in poetry install. new circle run as well.

# Description of changes
This adds the Bandit tool to the project, which scans for known security issues laid out by the tool. The tool is open source and can be found [here](https://github.com/PyCQA/bandit). It was found on the [OWASP](https://www.owasp.org/index.php/Source_Code_Analysis_Tools) website for Source Code Analysis Tools. 
There was a baseline Bandit report ran with json output file created and date-stamped for future reference. This baseline was created because currently Bandit has several false positives for code optimization issues on "asserts" in the tests. It also flags a hardcoded temp or tmp directory, again in the tests. Since this is just in tests, I chose to baseline all of these issues so future comparisons will ignore them and only new "issues" will arise.

# Issue Resolved
OC Projects Security initiative. Bandit is one step of many still in development.

## Screenshots/GIFs
N/A

2019-05-22 16:50 UTC, AllenAnthes requested changes

2019-05-22 16:50 UTC, AllenAnthes commented on pyproject.toml
> +bandit = "~1.5.1"
We only need this declared as a dev-dependency since it's not needed at runtime.

2019-05-22 16:50 UTC, AllenAnthes commented on pyproject.toml
> +bandit = "~1.5.1"
If you could move this entry up to keep things in alphabetical order, for no other reason than to appease my OCD, I'd really appreciate it  😊

2019-05-22 17:29 UTC, garyray-k reviewed
fat fingered the commit message but the changes were made.

2019-05-22 19:47 UTC, AllenAnthes requested changes

2019-05-22 19:47 UTC, AllenAnthes commented on .circleci/config.yml
> +          command: |
Looks like an indentation error failed the build here.  You can use their CLI tool for validating the config locally before committing.

https://circleci.com/docs/2.0/local-cli/#validate-a-circleci-config

2019-05-23 10:48 UTC, garyray-k commented
Looks like the same issue I was getting when I tried using CircleCI on my forked repo.
As far as I can tell, it runs fine until it hits the `/usr/local/bin/cc-test-reporter after-build -t coverage.py` line and then spits out the following. (this is just after the `poetry run coverage report` terminal output)
```
Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier
      --insecure                     send coverage insecurely (without HTTPS)
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/circleci/project")

Global Flags:
  -d, --debug   run in debug mode

Exited with code 255
```

2019-05-23 10:50 UTC, garyray-k commented
![Screen Shot 2019-05-23 at 6 49 45 AM](https://user-images.githubusercontent.com/39040273/58247193-01dd7d00-7d27-11e9-8aaa-865363ac16f4.png)

2019-05-23 16:56 UTC, AllenAnthes approved these changes

2019-05-26 03:27 UTC, merged